name: Test and build Client

on:
  push:
    branches: ["main"]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Build Server
        run: echo "Build Server"

  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Build Client
        run: echo "Build Client"