name: Teste

on:
  push:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          client:
            - '.client/**'
          server:
            - '.server/**'

  test-server:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.server == 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Verificar modificações
        id: diff
        run: echo ::set-output name=modified::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

      - name: Testar Server
        if: ${{ contains(steps.diff.outputs.modified, 'server/') }}
        run: echo "Executando testes do Server" && sleep 5

  test-client:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.client == 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Verificar modificações
        id: diff
        run: echo ::set-output name=modified::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

      - name: Testar Client
        if: ${{ contains(steps.diff.outputs.modified, 'client/') }}
        run: echo "Executando testes do Client" && sleep 5