name: Test Server

on:
  push:
    paths:
    - 'server/**'

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: echo "Server Test"